version: 0.0
os: windows
files:
- source: /ROOT.war
  destination: C:\tmp
hooks:
  BeforeInstall:
    - location: before-install.bat
      timeout: 900

  Install:
    - location: install.bat     
      timeout: 900

  AfterInstall:
    - location: after-install.bat     
      timeout: 900

  ApplicationStart:
    - location: application-start.bat
      timeout: 900