version: 0.0
os: windows
files:
- source: /ROOT.war
  destination: C:\tmp
hooks:
  BeforeInstall:
    - location: scripts\before-install.bat
      timeout: 900

  Install:
    - location: scripts\install.bat     
      timeout: 900

  AfterInstall:
    - location: scripts\after-install.bat     
      timeout: 900

  ApplicationStart:
    - location: scripts\application-start.bat
      timeout: 900