version: 0.2


phases:
  install:
    runtime-versions:
      java: openjdk8
  
  build:
    commands:
      - echo Build started on `date`
      - mvn -f web/pom.xml -P $BUILD_ENV_NAME clean package -X
    
artifacts:
  files: 
    - target/*.jar
    - scripts/*.sh
    - appspec.yml  
  name: WarDeployment
  discard-paths: yes
  
cache:
  paths:
    - '/root/.m2/**/*'
