version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
    
artifacts:
  files: 
    - target/ROOT.war
    - appspec.yml  
  name: WarDeployment
  discard-paths: yes
  
