version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
    
artifacts:
  files:
    - scripts/* 
    - target/ROOT.war
    - appspec.yml  
  name: WarDeployment
  discard-paths: yes
 
  secondary-artifacts:     
    WarUpload: 
      files: 
        - target/ROOT.war
      discard-paths: yes 
      name: WarUpload
  
cache:
  paths:
    - '/root/.m2/**/*'
